# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'ToDoMap' do

pod "Mapbox-iOS-SDK"

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5'

end

target 'ToDoMapTests' do

end

